### PR TITLE
support for >=time-1.5

### PR DESCRIPTION
**Pull request by larskuhtz**

### CODE REVIEW

**Comment by larskuhtz** [comment]
Thanks for merging this @aristidb. When are you planning an new Hackage release with this change?

**Comment by aristidb** [comment]
No plans yet.

Lars Kuhtz <notifications@github.com> schrieb am Do., 15. Jan. 2015 20:53:

**Comment by aristidb** [comment]
Done.

Aristid Breitkreuz <aristidb@gmail.com> schrieb am Thu Jan 15 2015 at
20:34:56:

**Comment by larskuhtz** [comment]
Thanks a lot! Unfortunately I forgot to relax the upper bound on time. Mea culpa. I'll submit a new PR for it.

**Comment by aristidb** [comment]
DOn't bother I'll just fix it

Lars Kuhtz <notifications@github.com> schrieb am Sun Jan 18 2015 at
21:58:24:

**Comment by aristidb** [comment]
Done

Aristid Breitkreuz <aristidb@gmail.com> schrieb am Sun Jan 18 2015 at
22:01:28:

**Comment by larskuhtz** [comment]
That was quick! Thanks!

**Pull request merged**
