### PR TITLE
Allow bytestring-0.11 + support aeson-2.0

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Comment by aristidb** [comment]
@Bodigrim I do not really have time to maintain this package anymore, but if somebody trustworthy steps up to do so I would be happy to transfer ownership.

**Comment by Bodigrim** [comment]
@aristidb unfortunately I know too little about AWS. Did you consider sending an email to libraries@haskell.org and/or haskell-cafe@haskell.org to find a new maintainer?

**Comment by aristidb** [comment]
@Bodigrim Do I need to subscribe to those mailing lists to send a mail there? Or will it send me replies to this inquiry without having to subscribe?

**Comment by Bodigrim** [comment]
You need to subscribe first:
https://mail.haskell.org/cgi-bin/mailman/listinfo/libraries
https://mail.haskell.org/cgi-bin/mailman/listinfo/haskell-cafe

**Comment by aristidb** [comment]
@Bodigrim Not joining mailing lists, but if you could please retweet this it might help? https://twitter.com/aristidb/status/1455273103278346244?s=21

**Comment by cartazio** [comment]
I might be interested in this, though it depends on a few life things i'm juggling this fall settling down over the next few weeks

**Comment by aristidb** [comment]
@cartazio Please do let me know once it's clear, I would be happy to transfer the project to you as I know that you've been in the Haskell community for quite a few years.

**Comment by Bodigrim** [comment]
As a Hackage trustee I made one more revision, this time allowing `attoparsec-0.14`: https://hackage.haskell.org/package/aws-0.22/revisions/

**Comment by Bodigrim** [comment]
I prefer to keep a list of my PRs actionable, so closing this as stalled.

**Pull request closed without merging**
